import { BookOutlined, CheckCircleOutlined, ClockCircleOutlined, SafetyCertificateOutlined, TeamOutlined } from '@ant-design/icons';
import { Card, Progress, Skeleton, Timeline } from 'antd';
import { PageHeader } from '../../components/common/PageHeader';
import { MetricCard } from '../../components/common/MetricCard';
import { useUsers } from '../../hooks/useUsers';
import { useCourses } from '../../hooks/useCourses';
import { useTrainingAssignments } from '../../hooks/useTrainingAssignments';
import { useCertificateIssues } from '../../hooks/useCertificateIssues';
import { useAssessmentAttempts } from '../../hooks/useAssessmentAttempts';
export function DashboardPage() { const users=useUsers(); const courses=useCourses(); const assignments=useTrainingAssignments(); const certs=useCertificateIssues(); const attempts=useAssessmentAttempts(); if([users,courses,assignments,certs,attempts].some(q=>q.isLoading)) return <Skeleton active />; const pending=assignments.data?.filter(a=>a.status!=='completed').length??0; const pass=attempts.data?.filter(a=>a.result_status==='passed').length??0; const passRate=attempts.data?.length?Math.round(pass/attempts.data.length*100):0; return <><PageHeader title="Dashboard" subtitle="Live mock KPIs powered through TanStack Query hooks."/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><MetricCard title="Total users" value={users.data?.length??0} icon={<TeamOutlined/>}/><MetricCard title="Active courses" value={courses.data?.filter(c=>c.is_active).length??0} icon={<BookOutlined/>}/><MetricCard title="Pending assignments" value={pending} icon={<ClockCircleOutlined/>}/><MetricCard title="Certificates" value={certs.data?.length??0} icon={<SafetyCertificateOutlined/>}/><MetricCard title="Pass rate" value={passRate} suffix="%" icon={<CheckCircleOutlined/>}/></div><div className="mt-5 grid gap-5 lg:grid-cols-3"><Card title="Training completion" className="page-card lg:col-span-2"><div className="space-y-4"><Progress percent={Math.round(((assignments.data?.filter(a=>a.status==='completed').length??0)/(assignments.data?.length||1))*100)} /><Progress percent={passRate} status="active" /></div></Card><Card title="Recent activity" className="page-card"><Timeline items={[{children:'Course assigned to David'},{children:'Password quiz passed'},{children:'Certificate issued'}]}/></Card></div></>; }
