import { Button, Drawer, Form, Input, Select, Space, message } from 'antd';
import { useState } from 'react';
import { DataTable } from '../../components/common/DataTable';
import { PageHeader } from '../../components/common/PageHeader';
import { StatusTag } from '../../components/common/StatusTag';
import { useCreateUser, useUsers } from '../../hooks/useUsers';
import { useRoles } from '../../hooks/useRoles';
import { findRole } from '../../utils/lookup';
export function UsersPage(){ const {data,isLoading}=useUsers(); const {data:roles}=useRoles(); const create=useCreateUser(); const [open,setOpen]=useState(false); return <><PageHeader title="User Management" subtitle="Search, create and manage learners, managers and admins." actions={<Button type="primary" onClick={()=>setOpen(true)}>Create user</Button>}/><DataTable loading={isLoading} dataSource={data} columns={[{title:'Name',dataIndex:'full_name'},{title:'Email',dataIndex:'email'},{title:'Employee Code',dataIndex:'employee_code'},{title:'Role',render:(_,r)=>findRole(roles,r.role_id)?.role_name},{title:'Status',render:(_,r)=><StatusTag value={r.status}/>}]}/><Drawer open={open} onClose={()=>setOpen(false)} title="Create user" width={480}><Form layout="vertical" onFinish={(v)=>create.mutate(v,{onSuccess:()=>{message.success('User created'); setOpen(false)}})}><Form.Item name="full_name" label="Full name" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="email" label="Email" rules={[{required:true,type:'email'}]}><Input/></Form.Item><Form.Item name="employee_code" label="Employee code"><Input/></Form.Item><Form.Item name="role_id" label="Role" rules={[{required:true}]}><Select options={roles?.map(r=>({label:r.role_name,value:r.role_id}))}/></Form.Item><Form.Item name="status" label="Status" initialValue="active"><Select options={[{label:'Active',value:'active'},{label:'Inactive',value:'inactive'}]}/></Form.Item><Space><Button htmlType="submit" type="primary" loading={create.isPending}>Save</Button><Button onClick={()=>setOpen(false)}>Cancel</Button></Space></Form></Drawer></>; }
